### ISSUE TITLE
Create burger style navigation for mobile users.

### ISSUE THREAD

**Issue by Edga380** [fac29b/Chibs-Eds-Agency#13]
-  [ ] Create button top right corner in the navigation bar. 
-  [ ] When pressed drop down menu appears with options.
-  [ ] Animate burger style so from 3 lines it changes to X.
-  [ ] Anime drop down menu.
-  [ ] When hover on links they change colour.

**Comment by ChibsDev** [comment]
tasklist on this issue have been fulfilled.  I accidentally left out the function to close the menu when a nav link is selected. I intend to close this issue after i have sorted that out .
